services:
  rabbitmq:
    image: rabbitmq:4.1.5-management-alpine
    container_name: rabbitmq-forecast
    hostname: rabbitmq
    restart: unless-stopped
    
    ports:
      - "5672:5672"   # AMQP protocol
      - "15672:15672" # Management UI
    
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    
    networks:
      - forecast-network
    
    environment:
      - RABBITMQ_VM_MEMORY_HIGH_WATERMARK=0.6  # Ограничение использования памяти до 60%
      - RABBITMQ_DEFAULT_VHOST=/
    
    deploy:
      resources:
        limits:
          memory: 1024M
        reservations:
          memory: 512M
    
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 40s
    
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  rabbitmq_init:
    image: rabbitmq:4.1.5-management-alpine
    container_name: rabbitmq-init
    restart: "no"
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file: ./secret/.env
    
    networks:
      - forecast-network
    
    deploy:
      resources:
        limits:
          memory: 256M
    
    entrypoint: >
      /bin/sh -c '
      sh /etc/init/init.sh;
      exit 0;
      '
    
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq # Used basically for shared cache with rabbitmq-forecast
      - ./init.sh:/etc/init/init.sh:ro # Mount init scripts