services:
  clickhouse:
    # Using latest for now, but in production it should be some stable version
    image: clickhouse:latest
    container_name: clickhouse-forecast
    hostname: clickhouse
    restart: unless-stopped
    env_file: ./secret/.env
    
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9004:9004"
      - "9009:9009"
    
    environment:
      - CLICKHOUSE_DB=forecast_main
      - CLICKHOUSE_USER=default # Used to access the DB and change its settings
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
    
    volumes:
      # Saving user configuration
      - clickhouse_users:/etc/clickhouse-server/users.d
      # Data storage
      - clickhouse_data:/var/lib/clickhouse
      # Config files
      - ./config.xml:/etc/clickhouse-server/config.d/custom-config.xml
      # Init scripts
      - ./init_users.sh:/docker-entrypoint-initdb.d/init-users.sh:ro
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    
    networks:
      - forecast-network
    
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8123/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"