services:
  clickhouse:
    # Using latest for now, later it will be some stable version
    image: clickhouse:latest
    container_name: clickhouse-forecast
    hostname: clickhouse
    restart: unless-stopped
    
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9004:9004"
      - "9009:9009"
    
    environment:
      - CLICKHOUSE_DB=forecast_main
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=/run/secrets/clickhouse_admin
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
    
    secrets:
      - clickhouse_admin
      - clickhouse_user
    
    volumes:
      # Saving user configuration
      - clickhouse_users:/etc/clickhouse-server/users.d
      # Data storage
      - clickhouse_data:/var/lib/clickhouse
      # Config files
      - ./clickhouse/config.xml:/etc/clickhouse-server/config.d/custom-config.xml
      # Init scripts
      - ./clickhouse/init_users.sh:/docker-entrypoint-initdb.d/init-users.sh:ro
      - ./clickhouse/init.sql:/docker-entrypoint-initdb.d/init.sql
    
    networks:
      - forecast-network
    
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8123/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  minio:
    image: minio/minio:latest
    container_name: minio-forecast
    hostname: minio
    restart: unless-stopped
    # Ports are changed from default because of Clickhouse
    ports:
      - "9101:9001"  # Console port
      - "9100:9000"  # API port
    
    environment:
      - MINIO_ROOT_USER_FILE=/run/secrets/minio_user
      - MINIO_ROOT_PASSWORD_FILE=/run/secrets/minio_password
      - MINIO_DEFAULT_BUCKETS=forecast-data
      - MINIO_DOMAIN=localhost
    
    volumes:
      - minio_data:/data
    
    command: server /data --console-address ":9001"
    
    networks:
      - forecast-network

    secrets:
      - minio_user
      - minio_password
    
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
      start_period: 40s
    
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  minio_init:
    image: minio/mc:latest
    container_name: minio-init
    restart: "no"
    depends_on:
      - minio

    environment:
      - MINIO_ROOT_USER_FILE=/run/secrets/minio_user
      - MINIO_ROOT_PASSWORD_FILE=/run/secrets/minio_password

    networks:
      - forecast-network

    secrets:
      - minio_user
      - minio_password

    entrypoint: >
      /bin/sh -c '
      sleep 5;
      sh /etc/minio/init/init.sh;
      exit 0;
      '

    volumes:
      - ./minio/init.sh:/etc/minio/init/init.sh:ro

volumes:
  # Explicitly declaring volumes
  clickhouse_users:
    external: false
  clickhouse_data:
    external: false
  minio_data:
    external: false

networks:
  forecast-network:
    driver: bridge
    name: forecast-network

secrets:
  clickhouse_admin:
    file: ./clickhouse/secret/db_root_password.txt
  clickhouse_user:
    file: ./clickhouse/secret/db_password.txt
  minio_user:
    file: ./minio/secret/minio_user.txt
  minio_password:
    file: ./minio/secret/minio_pass.txt