services:
  test_inserter:
    image: test_foxecast_inserter:1.0.0
    container_name: test_inserter
    env_file: ./secret/test_env/.env

    depends_on:
      clickhouse:
        condition: service_healthy
      minio:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - forecast-network

  inserter:
    image: foxecast_inserter:1.0.0
    container_name: inserter
    ports:
      - "8001:8000"
    env_file: ./secret/test_env/.env

    depends_on:
      test_inserter:
        condition: service_completed_successfully
      clickhouse:
        condition: service_healthy
      minio:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - forecast-network

    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 30s
      timeout: 20s
      retries: 3
      start_period: 40s