services:


  clickhouse:
    # Using latest for now, later it will be some stable version
    image: clickhouse:latest
    container_name: clickhouse-forecast
    hostname: clickhouse
    restart: unless-stopped
    env_file: ./clickhouse/secret/.env
    
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9004:9004"
      - "9009:9009"
    
    environment:
      - CLICKHOUSE_DB=forecast_main
      - CLICKHOUSE_USER=default # Used to access the DB and change its settings
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
    
    # secrets:
    #   - clickhouse_admin
    #   - clickhouse_user
    
    volumes:
      # Saving user configuration
      - clickhouse_users:/etc/clickhouse-server/users.d
      # Data storage
      - clickhouse_data:/var/lib/clickhouse
      # Config files
      - ./clickhouse/config.xml:/etc/clickhouse-server/config.d/custom-config.xml
      # Init scripts
      - ./clickhouse/init_users.sh:/docker-entrypoint-initdb.d/init-users.sh:ro
      - ./clickhouse/init.sql:/docker-entrypoint-initdb.d/init.sql
    
    networks:
      - forecast-network
    
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8123/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  minio:
    image: minio/minio:latest
    container_name: minio-forecast
    hostname: minio
    restart: unless-stopped
    # Ports are changed from default because of Clickhouse
    ports:
      - "9101:9001"  # Console port
      - "9100:9000"  # API port
    env_file: ./minio/secret/.env
    
    environment:
      - MINIO_DEFAULT_BUCKETS=forecast-data
      - MINIO_DOMAIN=localhost # Used as domain inside the container
    
    volumes:
      - minio_data:/data
    
    command: server /data --console-address ":9001"
    
    networks:
      - forecast-network
    
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9000/minio/health/live || exit 1"]
      interval: 30s
      timeout: 20s
      retries: 3
      start_period: 40s
    
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  minio_init:
    image: minio/mc:latest
    container_name: minio-init
    restart: "no"
    depends_on:
      - minio
    env_file: ./minio/secret/.env

    networks:
      - forecast-network

    entrypoint: >
      /bin/sh -c '
      sleep 5;
      sh /etc/minio/init/init.sh;
      exit 0;
      '

    volumes:
      - ./minio/init.sh:/etc/minio/init/init.sh:ro

  rabbitmq:
    image: rabbitmq:4.1.5-management-alpine
    container_name: rabbitmq-forecast
    hostname: rabbitmq
    restart: unless-stopped
    
    ports:
      - "5672:5672"   # AMQP protocol
      - "15672:15672" # Management UI
    
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    
    networks:
      - forecast-network
    
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 40s
    
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  rabbitmq_init:
    image: rabbitmq:4.1.5-management-alpine
    container_name: rabbitmq-init
    restart: "no"
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file: ./rabbitmq/secret/.env
    
    networks:
      - forecast-network
    
    entrypoint: >
      /bin/sh -c '
      sh /etc/init/init.sh;
      exit 0;
      '
    
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq # Used basically for shared cache with rabbitmq-forecast
      - ./rabbitmq/init.sh:/etc/init/init.sh:ro # Mount init scripts

volumes:
  # Explicitly declaring volumes
  clickhouse_users:
    external: false
  clickhouse_data:
    external: false
  minio_data:
    external: false
  rabbitmq_data:
    external: false

networks:
  forecast-network:
    driver: bridge
    name: forecast-network

secrets:
  clickhouse_admin:
    file: ./clickhouse/secret/db_root_password.txt
  clickhouse_user:
    file: ./clickhouse/secret/db_password.txt

  minio_user:
    file: ./minio/secret/minio_user.txt
  minio_password:
    file: ./minio/secret/minio_pass.txt

  rabbitmq_user:
    file: ./rabbitmq/secret/rabbitmq_user.txt
  rabbitmq_pass:
    file: ./rabbitmq/secret/rabbitmq_pass.txt

  inserter_main:
    file: ./inserter/secret/main.env
  inserter_test:
    file: ./inserter/secret/.env
