# It is recommended to use Docker Compose version 3.8+ because of
# some attributes, unsupported in older versions (e.g. 'include')

# Including submodules to the main compose file
include:
  - path: ./inserter/compose.yml
  - path: ./clickhouse/compose.yml
  - path: ./minio/compose.yml
  - path: ./rabbitmq/compose.yml

# All services should be added as separate modules through 'include'

volumes:
  # Explicitly declaring volumes
  clickhouse_users:
    external: false
  clickhouse_data:
    external: false
  minio_data:
    external: false
  rabbitmq_data:
    external: false

networks:
  forecast-network:
    driver: bridge
    name: forecast-network
